<?php

return [
    'source' => [
        'enabled' => env('MY_LOCATIONS_REMOTE_ENABLED', true),
        'url' => env('MY_LOCATIONS_REMOTE_URL', 'https://storage.dosm.gov.my/population/population_district.csv'),
        'cache_ttl_minutes' => env('MY_LOCATIONS_CACHE_TTL_MINUTES', 10080),
    ],

    'popular_areas' => [
        'Selangor' => [
            'Ampang Jaya',
            'Bandar Baru Bangi',
            'Cyberjaya',
            'Kajang',
            'Petaling Jaya',
            'Puchong',
            'Rawang',
            'Selayang',
            'Serdang',
            'Seri Kembangan',
            'Shah Alam',
            'Subang Jaya',
        ],
        'W.P. Kuala Lumpur' => [
            'Bangsar',
            'Bukit Jalil',
            'Cheras',
            'Desa ParkCity',
            'Jalan Ipoh',
            'KL City Centre',
            'Kepong',
            'Mont Kiara',
            'Setapak',
            'Sri Petaling',
            'Wangsa Maju',
        ],
        'Johor' => [
            'Iskandar Puteri',
            'Skudai',
        ],
        'Pulau Pinang' => [
            'Air Itam',
            'Bayan Lepas',
            'Bukit Mertajam',
            'Nibong Tebal',
        ],
        'Sabah' => [
            'Inanam',
            'Likas',
            'Putatan',
        ],
    ],

    'states' => [
        'Johor' => [
            'Batu Pahat',
            'Johor Bahru',
            'Kluang',
            'Kota Tinggi',
            'Kulai',
            'Mersing',
            'Muar',
            'Pontian',
            'Segamat',
            'Tangkak',
        ],
        'Kedah' => [
            'Baling',
            'Bandar Baharu',
            'Kota Setar',
            'Kuala Muda',
            'Kubang Pasu',
            'Kulim',
            'Langkawi',
            'Padang Terap',
            'Pendang',
            'Pokok Sena',
            'Sik',
            'Yan',
        ],
        'Kelantan' => [
            'Bachok',
            'Gua Musang',
            'Jeli',
            'Kota Bharu',
            'Kuala Krai',
            'Machang',
            'Pasir Mas',
            'Pasir Puteh',
            'Tanah Merah',
            'Tumpat',
        ],
        'Melaka' => [
            'Alor Gajah',
            'Jasin',
            'Melaka Tengah',
        ],
        'Negeri Sembilan' => [
            'Jelebu',
            'Jempol',
            'Kuala Pilah',
            'Port Dickson',
            'Rembau',
            'Seremban',
            'Tampin',
        ],
        'Pahang' => [
            'Bentong',
            'Bera',
            'Cameron Highlands',
            'Jerantut',
            'Kuantan',
            'Lipis',
            'Maran',
            'Pekan',
            'Raub',
            'Rompin',
            'Temerloh',
        ],
        'Perak' => [
            'Batang Padang',
            'Hilir Perak',
            'Hulu Perak',
            'Kampar',
            'Kerian',
            'Kinta',
            'Kuala Kangsar',
            'Larut Matang dan Selama',
            'Manjung',
            'Muallim',
            'Perak Tengah',
        ],
        'Perlis' => [
            'Kangar',
        ],
        'Pulau Pinang' => [
            'Barat Daya',
            'Seberang Perai Selatan',
            'Seberang Perai Tengah',
            'Seberang Perai Utara',
            'Timur Laut',
        ],
        'Sabah' => [
            'Beaufort',
            'Beluran',
            'Keningau',
            'Kinabatangan',
            'Kota Belud',
            'Kota Kinabalu',
            'Kota Marudu',
            'Kuala Penyu',
            'Kudat',
            'Kunak',
            'Lahad Datu',
            'Nabawan',
            'Papar',
            'Penampang',
            'Pitas',
            'Ranau',
            'Sandakan',
            'Semporna',
            'Sipitang',
            'Tambunan',
            'Tawau',
            'Telupid',
            'Tenom',
            'Tongod',
            'Tuaran',
        ],
        'Sarawak' => [
            'Betong',
            'Bintulu',
            'Kapit',
            'Kuching',
            'Limbang',
            'Miri',
            'Mukah',
            'Samarahan',
            'Sarikei',
            'Serian',
            'Sibu',
            'Sri Aman',
        ],
        'Selangor' => [
            'Gombak',
            'Hulu Langat',
            'Hulu Selangor',
            'Klang',
            'Kuala Langat',
            'Kuala Selangor',
            'Petaling',
            'Sabak Bernam',
            'Sepang',
        ],
        'Terengganu' => [
            'Besut',
            'Dungun',
            'Hulu Terengganu',
            'Kemaman',
            'Kuala Nerus',
            'Kuala Terengganu',
            'Marang',
            'Setiu',
        ],
        'W.P. Kuala Lumpur' => [
            'Bukit Bintang',
            'Cheras',
            'Kepong',
            'Lembah Pantai',
            'Segambut',
            'Setiawangsa',
            'Titiwangsa',
            'Wangsa Maju',
        ],
        'W.P. Labuan' => [
            'Labuan',
        ],
        'W.P. Putrajaya' => [
            'Putrajaya',
        ],
    ],
];
